// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EditUser(arg1:string):Promise<void>;

export function GetByte(arg1:string):Promise<Array<number>>;

export function GetString(arg1:Array<number>):Promise<string>;

export function GetUser():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenFile():Promise<string>;

export function Read(arg1:string):Promise<Array<number>>;

export function Schedule(arg1:number,arg2:string,arg3:string):Promise<boolean>;

export function ShowInfo(arg1:string,arg2:string):Promise<string>;

export function Stats(arg1:string):Promise<main.Info>;

export function Write(arg1:string,arg2:Array<number>):Promise<void>;
