// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function Read(arg1) {
  return window['go']['main']['App']['Read'](arg1);
}

export function Stats(arg1) {
  return window['go']['main']['App']['Stats'](arg1);
}

export function Write(arg1, arg2) {
  return window['go']['main']['App']['Write'](arg1, arg2);
}
