// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SayAgenName(arg1, arg2) {
  return window['go']['main']['User']['SayAgenName'](arg1, arg2);
}
