name: Wails build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: Callie, platform: linux/amd64, os: ubuntu-latest},
          {name: Callie, platform: windows/amd64, os: windows-latest},
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        if: matrix.build.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            pkg-config \
            build-essential   
       # Install dependencies (ensure Go and Node.js are installed)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Use your preferred Go version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      # Install Wails
      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor  
      - name: Add Secret  
        shell: bash
        run:  echo ${{ secrets.MONGO_URI }} > secret.txt 
      - name: Build Wails app
        run: |
           wails build -platform ${{ matrix.build.platform }} -webview2 download
      - uses: actions/upload-artifact@v4
        with:
          name: Callie-${{ matrix.build.platform }}
          path: ./build/bin/      
      
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup GoLang
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: 'stable'
      - run: go version
        shell: bash
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Add Secret
        shell: bash
        run:  echo ${{ secrets.MONGO_URI }} > secret.txt    
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Install macOS Wails deps
        run: brew install mitchellh/gon/gon nsis
        shell: bash
      - name: Build app
        shell: bash
        run: |
          wails build --platform darwin/universal -webview2 download
          ditto -c -k ./build/bin/Callie.app ./build/bin/Callie.app.zip
      - name: Building Installer
        shell: bash
        run: |
          productbuild --component ./build/bin/Callie.app ./build/bin/Callie.pkg
      - uses: actions/upload-artifact@v4
        with:
          name: mac-artifact
          path: ./build/bin/    