name: Release Linux

on:   
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
        default: '0.0.1'

jobs:
  build-linux: 
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/arm64
          - linux/amd64
        include:
          - os: linux-latest
            platform: linux/amd64
            build-name: Callie-linux
    runs-on: linux-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            pkg-config \
            build-essential
      # Install dependencies (ensure Go and Node.js are installed)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Use your preferred Go version

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use your preferred Node.js version

      # Install Wails
      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails doctor  # Ensure Wails is set up correctly
      
      - name: Add Secret
        shell: bash
        run: echo ${{ secrets.MONGO_URI }} > secret.txt 
        
      # Build the Wails app
      - name: Build Wails app
        run: |
          wails build -platform ${{ matrix.platform }}

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build-name }}-binary
          path: ./build/bin/Callie # Adjust to your actual build output path
  release-linux:
    needs: build-linux
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows binary
        uses: actions/download-artifact@v3
        with:
          name: Callie-linux-binary 

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: ./Callie-linux-binary  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 